const UPDATE_USER_SETTINGS = 'UPDATE_USER_SETTINGS',
  MODIFY_PERIOD = 'MODIFY_PERIOD',
  CREATE_PERIOD = 'CREATE_PERIOD',
  ADD_SPENDING = 'ADD_SPENDING',
  DELETE_SPENDING = 'DELETE_SPENDING'

export default {
  UPDATE_USER_SETTINGS,
  MODIFY_PERIOD,
  CREATE_PERIOD,
  ADD_SPENDING,
  DELETE_SPENDING,
}
